export const XP_RULES = Object.freeze({
  TASK_COMPLETION: { amount: 10, dailyCap: 50 },
  HABIT_COMPLETION: { amount: 10, dailyCap: 50 },
  GOAL_MILESTONE: { amount: 25, dailyCap: 50 },
  FOCUS_SESSION: { dailyCap: 80, minimumSeconds: 300, secondsPerXP: 150 },
});

export const STREAK_REWARDS = [
  { days: 7, xp: 50 },
  { days: 14, xp: 100 },
  { days: 30, xp: 250 },
  { days: 60, xp: 500 },
  { days: 100, xp: 1000 },
];

export const LEVEL_NAMES = [
  { level: 1, name: 'Newcomer' },
  { level: 5, name: 'Explorer' },
  { level: 10, name: 'Locked In' },
  { level: 20, name: 'Consistent' },
  { level: 30, name: 'Builder' },
  { level: 50, name: 'Veteran' },
  { level: 75, name: 'Elite' },
  { level: 100, name: 'Legend' },
];

export const MINIMUM_RANKED_TASKS = 10;

// Creation never earns XP. The first habit/goal awards require actual completion.
export const ACHIEVEMENTS = [
  {
    key: 'FIRST_TASK',
    name: 'First victory',
    description: 'Complete your first XP-eligible planned task.',
    icon: 'sword',
    xpReward: 25,
    metric: 'tasks',
    target: 1,
  },
  {
    key: 'FIRST_FOCUS',
    name: 'In the zone',
    description: 'Finish your first server-timed focus session of at least 5 minutes.',
    icon: 'focus',
    xpReward: 25,
    metric: 'focusSeconds',
    target: 300,
  },
  {
    key: 'FIRST_HABIT',
    name: 'A new ritual',
    description: 'Meet your first habit target.',
    icon: 'gem',
    xpReward: 25,
    metric: 'habits',
    target: 1,
  },
  {
    key: 'FIRST_GOAL',
    name: 'Mission accomplished',
    description: 'Complete every milestone of a goal with at least one milestone.',
    icon: 'flag',
    xpReward: 50,
    metric: 'goals',
    target: 1,
  },
  {
    key: 'FIRST_MILESTONE',
    name: 'One step closer',
    description: 'Complete your first goal milestone.',
    icon: 'flag',
    xpReward: 25,
    metric: 'milestones',
    target: 1,
  },
  {
    key: 'SEVEN_DAY_STREAK',
    name: 'Seven-day spark',
    description: 'Build a 7-day productivity streak.',
    icon: 'flame',
    xpReward: 0,
    metric: 'streak',
    target: 7,
  },
  {
    key: 'FOURTEEN_DAY_STREAK',
    name: 'Momentum maker',
    description: 'Build a 14-day productivity streak.',
    icon: 'flame',
    xpReward: 0,
    metric: 'streak',
    target: 14,
  },
  {
    key: 'THIRTY_DAY_STREAK',
    name: 'Unstoppable',
    description: 'Build a 30-day productivity streak.',
    icon: 'crown',
    xpReward: 0,
    metric: 'streak',
    target: 30,
  },
  {
    key: 'SIXTY_DAY_STREAK',
    name: 'Iron resolve',
    description: 'Build a 60-day productivity streak.',
    icon: 'shield',
    xpReward: 0,
    metric: 'streak',
    target: 60,
  },
  {
    key: 'HUNDRED_DAY_STREAK',
    name: 'Century legend',
    description: 'Build a 100-day productivity streak.',
    icon: 'crown',
    xpReward: 0,
    metric: 'streak',
    target: 100,
  },
  {
    key: 'TEN_FOCUS_HOURS',
    name: 'Deep-work explorer',
    description: 'Accumulate 10 hours of server-timed focus.',
    icon: 'focus',
    xpReward: 100,
    metric: 'focusSeconds',
    target: 36000,
  },
  {
    key: 'HUNDRED_FOCUS_HOURS',
    name: 'Focus master',
    description: 'Accumulate 100 hours of server-timed focus.',
    icon: 'focus',
    xpReward: 250,
    metric: 'focusSeconds',
    target: 360000,
  },
  {
    key: 'HUNDRED_TASKS',
    name: 'Century builder',
    description: 'Earn task XP on 100 distinct planned tasks.',
    icon: 'sword',
    xpReward: 100,
    metric: 'tasks',
    target: 100,
  },
  {
    key: 'FIVE_HUNDRED_TASKS',
    name: 'Master builder',
    description: 'Earn task XP on 500 distinct planned tasks.',
    icon: 'shield',
    xpReward: 250,
    metric: 'tasks',
    target: 500,
  },
];
